on: [push]

name: CI

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - run: pip install flake8
      - name: Check Formatting
        run: rustfmt --check src/*rs
      - name: Flake8
        run: flake8 tests
  
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run maturin develop
      - run: pipenv run pytest -v tests

